version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            docker-nginx-php:
                ipv4_address: 172.17.0.3
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes:
            - ./src:/src
        networks:
            - docker-nginx-php

networks:
    docker-nginx-php:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.17.0.0/30
                  gateway: 172.17.0.1
